name = "parkbeat"
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat"]
main = "src/server/index.ts"

# Bind R2 bucket
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "parkbeat-images"
preview_bucket_name = "parkbeat-images-dev"

[vars]
# Reference environment variables without exposing them in the file
DATABASE_URL = ""
R2_BUCKET_NAME = "parkbeat-images"

[dev]
port = 8080

[[durable_objects.bindings]]
name = "WEBSOCKET_DO"
class_name = "WebSocketDO"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketDO"]