name = "parkbeat"
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat"]
main = "src/server/index.ts"

# Bind R2 bucket
[[r2_buckets]]
binding = "R2"
bucket_name = "parkbeat"

[vars]
# Reference environment variables without exposing them in the file
R2_BUCKET_NAME = "parkbeat"
STORAGE_DOMAIN = "https://pub-1b329c4b7260459ab85c7d45a2c4dc12.r2.dev"
[dev]
port = 8080

[[durable_objects.bindings]]
name = "WEBSOCKET_DO"
class_name = "WebSocketDO"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketDO"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.